btn_go_to_cart ="//*[@class='shopping_cart_link']"
btn_proceed_to_checkout ="//*[@id='checkout']"
txt_box_firstname = "//*[@id = 'first-name']"
txt_box_lastname = "//*[@id = 'last-name']"
txt_box_zipcode = "//*[@id = 'postal-code']"
btn_continue_to_payment = "//*[@id = 'continue']"
btn_finish_payment = "//*[@id = 'finish']"
txt_checkout_message = "//*[@class='complete-text']"
btn_back_to_home = "//*[@id='back-to-products']"
